language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.4.22
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.11
  - DJANGO=1.8.14
  - DJANGO=1.9.9
  - DJANGO=1.10.1
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7.11
    - python: "2.6"
      env: DJANGO=1.8.14
    - python: "2.6"
      env: DJANGO=1.9.9
    - python: "2.6"
      env: DJANGO=1.10.1
    - python: "3.3"
      env: DJANGO=1.4.22
    - python: "3.4"
      env: DJANGO=1.4.22
    - python: "3.5"
      env: DJANGO=1.4.22
    - python: "3.3"
      env: DJANGO=1.5.12
    - python: "3.4"
      env: DJANGO=1.5.12
    - python: "3.5"
      env: DJANGO=1.5.12
    - python: "3.4"
      env: DJANGO=1.6.11
    - python: "3.5"
      env: DJANGO=1.6.11
    - python: "3.5"
      env: DJANGO=1.7.11
    - python: "3.3"
      env: DJANGO=1.9.9
    - python: "3.3"
      env: DJANGO=1.10.1

install:
  - pip install -q Django==$DJANGO
  - pip install tox coveralls

script:
  - coverage erase
  - PYTHONPATH=. coverage run -p example/run_tests.py
  - PYTHONPATH=. coverage run -p example/run_tests.py example.settings_no_debug
after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - goinnn@gmail.com
    - blag@users.noreply.github.com
